---
name: Image Cleanup
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Alpine Mainline, Alpine Stable, Debian Mainline, Debian Stable]
    types: [completed]
jobs:
  cleanup:
    name: Delete untagged NGINX Unprivileged Docker images on the Amazon ECR Public Gallery and the GitHub Container Registry
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get secrets from Azure
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: ${{secrets.NGINX_OSS_CLIENT_ID}}
          tenant-id: ${{secrets.NGINX_OSS_TENANT_ID}}
          vault-name: ${{secrets.NGINX_OSS_VAULT_NAME}}
          secret-names: "github-docker-nginx-unprivileged-public-ecr-aws-region, github-docker-nginx-unprivileged-public-ecr-aws-role-rw"
          env-names: "AWS_REGION, AWS_ROLE_ECR_PUBLIC_RW"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ECR_PUBLIC_RW }}
          role-duration-seconds: 3600

      - name: Delete untagged NGINX Unprivileged Docker images on the Amazon ECR Public Gallery
        run: |
          .github/workflows/scripts/delete-untagged-amazon-public-ecr-images.sh

      - name: Delete untagged NGINX Unprivileged Docker images on the GitHub Container Registry
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          package: nginx-unprivileged
          delete-ghost-images: true
          delete-untagged: true
          delete-partial-images: true
          delete-orphaned-images: true
          older-than: 2 years
          token: ${{ secrets.GITHUB_TOKEN }}
          validate: true
